# Generated by Django 3.2.1 on 2024-01-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='../static/images/avatar.svg', null=True, upload_to=''),
        ),
    ]
