# Generated by Django 4.0.3 on 2023-11-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jango', '0003_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registrations',
        ),
    ]
